gui:
  mouseEvents: false
  theme:
    activeBorderColor:
      - '#ff0000'
      - bold
    inactiveBorderColor:
      - '#e600ff'
  nerdFontsVersion: "3"
  spinner:
    frames:
      - ''
      - ''
    rate: 500

git:
  overrideGpg: true
  parseEmoji: true

os:
  editPreset: "nvim"
